[package]
name = "rtps-Python"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
lazy_static = "1"

serde = { version = "1", features = ["derive"] }
postcard = "1"
derive_more = { version = "1.0.0", features = ["from"] }

socket2 = { version = "0.5", features = ["all"] }
