name: build
on: [push]

jobs:
    build-linux:
        name: ${{matrix.os}} build
        runs-on: ${{matrix.os}}-latest
        strategy:
            fail-fast: false
            matrix:
                rust: [stable]
                os: [ubuntu, windows]
        timeout-minutes: 45
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@master
          with:
            toolchain: ${{matrix.rust}}
        - run: cargo build --release
        - uses: actions/upload-artifact@v4
          with:
            name: ros3
            path: target/release/ros3
          continue-on-error: true
